"""Emit the commit span for a commit the workflow has just made.

    python -m agentcore.emit_commit --result /tmp/result.json \
        --repo github.com/owner/name --sha "$(git rev-parse HEAD)"

A separate entry point because the SHA does not exist when the agent finishes. The
harness returns a patch; the workflow applies and commits it, and only then is there
a commit to attribute. codeburn's own emission splits the same way for the same
reason.

The trace and session ids come from the result.json that `agentcore.invoke` wrote.
They are not regenerated here: the receiver decides whether a commit is
AI-generated by looking for usage spans that share its trace id, so a fresh id would
record the agent's own commit as human-authored -- silently, and permanently, since
the receiver freezes origin at ingest and refuses ai→human downgrades but not the
reverse.

Exits 0 even when nothing was emitted. A missing collector or an unreachable one is
a reporting gap, not a reason to fail a workflow that has already produced a
reviewed fix.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from .telemetry import emit_commit


def main() -> int:
    parser = argparse.ArgumentParser(
        prog="agentcore.emit_commit",
        description="Emit the PRISM commit-attribution span for an agent commit.",
    )
    parser.add_argument("--result", required=True,
                        help="result.json from agentcore.invoke (carries the trace id)")
    parser.add_argument("--repo", required=True,
                        help="Host-qualified repo, e.g. github.com/owner/name")
    parser.add_argument("--sha", required=True, help="The commit SHA")
    parser.add_argument("--project", default="", help="Subdirectory, if a monorepo")
    parser.add_argument("--in-main", action="store_true",
                        help="Only for a commit already on the default branch")
    args = parser.parse_args()

    path = Path(args.result)
    if not path.exists():
        print(f"emit_commit: {path} not found; nothing to correlate against",
              file=sys.stderr)
        return 0

    try:
        result = json.loads(path.read_text())
    except json.JSONDecodeError as exc:
        print(f"emit_commit: {path} is not valid JSON ({exc}); skipping",
              file=sys.stderr)
        return 0

    trace_id = result.get("trace_id") or ""
    session_id = result.get("session_id") or ""
    issue_number = 0
    # The issue number is not in result.json today; accept it from the environment
    # so the workflow can pass what it already knows without a schema change.
    try:
        issue_number = int(result.get("issue_number") or 0)
    except (TypeError, ValueError):
        issue_number = 0

    emit_commit(
        repo=args.repo,
        sha=args.sha,
        trace_id=trace_id,
        session_id=session_id,
        project=args.project or args.repo,
        issue_number=issue_number,
        in_main=args.in_main,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
